# Generated by Django 4.2.6 on 2024-06-29 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='options',
            new_name='option_text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='questions',
            new_name='question_text',
        ),
        migrations.RemoveField(
            model_name='option',
            name='question',
        ),
        migrations.RemoveField(
            model_name='response',
            name='option',
        ),
        migrations.AddField(
            model_name='question',
            name='option_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option_values',
            field=models.ManyToManyField(blank=True, to='forms.option'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('SHORT', 'Short Paragraph'), ('LONG', 'Long Paragraph'), ('MULTIPLE', 'Multiple Choices'), ('CHECKBOX', 'Checkboxes')], default='SHORT', max_length=10),
        ),
        migrations.AddField(
            model_name='response',
            name='checkbox_options',
            field=models.ManyToManyField(blank=True, related_name='checkbox_responses', to='forms.option'),
        ),
        migrations.AddField(
            model_name='response',
            name='long_response_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='multiple_choice_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multiple_choice_responses', to='forms.option'),
        ),
        migrations.AddField(
            model_name='response',
            name='short_response_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
